eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.4:3306/SpringCloud_Sell?characterEncoding=utf-8
    username: root
    password: Osming07.
  jpa:
    show-sql: true
env:
  dev
